POST http://localhost:9244/member/login HTTP/1.1 
content-type: application/json

{
   "miId" : "user19",
   "miPwd" : "57735773"
}
#################################################
PUT http://localhost:9244/member/join HTTP/1.1
content-type: application/json

{
  "miId" : "user18", 
  "miPwd" : "92449244!", 
  "miEmail" : "user018@naver.com", 
  "miPhone" : "01090019244", 
  "miNickname" : "차대희", 
  "miAddress" : "대구시 중구 삼덕동1가 1-2", 
  "miStatus" : "0"
}
#################################################
POST http://localhost:9244/member/searchId HTTP/1.1
content-type: application/json

{
   "miPhone" : "01090009244"
}
#################################################

POST http://localhost:9244/member/dupchkId HTTP/1.1
content-type: application/json

{
   "miId" : "user30"
}
##################################################
POST http://192.168.0.9:9244/member/searchPwd HTTP/1.1
content-type: application/json

{
   "miId" : "user1",
   "miPhone" : "01012345678"
}
#################################################
POST http://localhost:9244/member/deleteMember HTTP/1.1
content-type: application/json

{
  "miPwd" : "92449244"
}
#################################################
PUT http://192.168.0.9:9244/review/write?miSeq=2 HTTP/1.1
content-type: application/json

{
"score" : 5, 
"content" : "적당해요", 
"oiSeq" : "7GTCHSzMiT", 
"tasteScore" : 5, 
"quantityScore" : 5, 
"deliveryScore" : 5
}

